### ISSUE TITLE
The package fbprophet cannot be installed on my device

### ISSUE THREAD

**Issue by ireversekay** [rdemarqui/traffic_prediction_and_congestion#1]
we tried downloading the package and it will not be installed and looked through youtube and no luck, i hope you have a solution
![WhatsApp Image 2023-12-31 at 17 27 28_24917c36](https://github.com/rdemarqui/traffic_prediction_and_congestion/assets/154887758/2d8fceb6-a95e-4cfe-894b-0095bfdac573)
![WhatsApp Image 2023-12-31 at 17 27 19_104b5bd7](https://github.com/rdemarqui/traffic_prediction_and_congestion/assets/154887758/b0a53772-c656-49a0-afc0-cf41445a4834)

**Comment by rdemarqui** [comment]
Hi.
Try `pip install prophet` instead of `fbprophet`. It should work.

![image](https://github.com/rdemarqui/traffic_prediction_and_congestion/assets/21056133/228eb450-9f8f-4546-9bf7-d8f79dda8bb7)

**Comment by rdemarqui** [comment]
I fixed the code with the update of the prophet package so that it can run 100% on Google Colab.
