### ISSUE TITLE
 How to Change or Obtain Similar Datasets for LTE Traffic Forecasting

### ISSUE THREAD

**Issue by gebril104** [rdemarqui/traffic_prediction_and_congestion#2]
I am working with the LTE Cell Traffic Growth and Congestion Forecasting notebook and need guidance on modifying the `datasets` used in the code. I would like to:
1. Know the steps required to replace the current dataset with a different one.
2. Find similar datasets that would be compatible with the code for LTE traffic forecasting.
.

**Comment by rdemarqui** [comment]
If you are running on Google Colab, you need to upload your data (see how here: https://stackoverflow.com/questions/46986398/import-data-into-google-colaboratory) and change the snippet below:

daily_traffic = pd.read_csv(os.path.join(current_dir, 'your_file_here.csv'), sep=';')
...
hourly_traffic = pd.read_csv(os.path.join(current_dir, 'df_hourly_sample.csv'), sep=';')

I don't know where you can find similar data, probably if you get in touch with somebody that works at a mobile operator.
